version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
     - "5001:5001"
    networks:
     - oedatamodel
    env_file:
      - ./.envs/.production/.fastapi

  redis:
    image: redis:6.2
    networks:
      - oedatamodel

networks:
  oedatamodel:
